version: 2.1 

workflows:
  version: 2
  Verify:
    jobs:
      - test

jobs: 
  test: 
    working_directory: ~/repo
    docker: # run the steps with Docker
      - image: circleci/node:12.4.0
      - image: gitlab/gitlab-ce
    environment:
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
