var merge_requests = [
    {
      "id": 103359,
      "iid": 4,
      "project_id": 9170,
      "title": "add tags to coredns",
      "description": "```------------------------------------------------------------------------\n\nAn execution plan has been generated and is shown below.\nResource actions are indicated with the following symbols:\n  ~ update in-place\n-/+ destroy and then create replacement\n\nTerraform will perform the following actions:\n\n  ~ module.coredns.aws_network_interface.coredns-eni[0]\n      tags.%:                      \"6\" => \"14\"\n      tags.AppRole:                \"\" => \"CoreDNS\"\n      tags.Approval:               \"\" => \"Yes\"\n      tags.Channel:                \"\" => \"Cloud Services\"\n      tags.Compliance:             \"\" => \"NCDE\"\n      tags.CostCentre:             \"\" => \"C958958\"\n      tags.Environment:            \"\" => \"dev\"\n      tags.Escalation:             \"\" => \"Albie.VanDerMerwe@williamhill.com\"\n      tags.InstanceReplacement:    \"\" => \"true\"\n      tags.Owner:                  \"\" => \"Cloud Services\"\n      tags.Product:                \"\" => \"CoreDNS\"\n      tags.Tier:                   \"\" => \"Internal\"\n      tags.Version:                \"\" => \"1.28.0\"\n      tags.approle:                \"Core DNS\" => \"\"\n      tags.compliance:             \"NCDE\" => \"\"\n      tags.product:                \"dns\" => \"\"\n      tags.tier:                   \"internal\" => \"\"\n\n  ~ module.coredns.aws_network_interface.coredns-eni[1]\n      tags.%:                      \"6\" => \"14\"\n      tags.AppRole:                \"\" => \"CoreDNS\"\n      tags.Approval:               \"\" => \"Yes\"\n      tags.Channel:                \"\" => \"Cloud Services\"\n      tags.Compliance:             \"\" => \"NCDE\"\n      tags.CostCentre:             \"\" => \"C958958\"\n      tags.Environment:            \"\" => \"dev\"\n      tags.Escalation:             \"\" => \"Albie.VanDerMerwe@williamhill.com\"\n      tags.InstanceReplacement:    \"\" => \"true\"\n      tags.Owner:                  \"\" => \"Cloud Services\"\n      tags.Product:                \"\" => \"CoreDNS\"\n      tags.Tier:                   \"\" => \"Internal\"\n      tags.Version:                \"\" => \"1.28.0\"\n      tags.approle:                \"Core DNS\" => \"\"\n      tags.compliance:             \"NCDE\" => \"\"\n      tags.product:                \"dns\" => \"\"\n      tags.tier:                   \"internal\" => \"\"\n\n  ~ module.coredns.aws_network_interface.coredns-eni[2]\n      tags.%:                      \"6\" => \"14\"\n      tags.AppRole:                \"\" => \"CoreDNS\"\n      tags.Approval:               \"\" => \"Yes\"\n      tags.Channel:                \"\" => \"Cloud Services\"\n      tags.Compliance:             \"\" => \"NCDE\"\n      tags.CostCentre:             \"\" => \"C958958\"\n      tags.Environment:            \"\" => \"dev\"\n      tags.Escalation:             \"\" => \"Albie.VanDerMerwe@williamhill.com\"\n      tags.InstanceReplacement:    \"\" => \"true\"\n      tags.Owner:                  \"\" => \"Cloud Services\"\n      tags.Product:                \"\" => \"CoreDNS\"\n      tags.Tier:                   \"\" => \"Internal\"\n      tags.Version:                \"\" => \"1.28.0\"\n      tags.approle:                \"Core DNS\" => \"\"\n      tags.compliance:             \"NCDE\" => \"\"\n      tags.product:                \"dns\" => \"\"\n      tags.tier:                   \"internal\" => \"\"\n\n  ~ module.coredns.aws_security_group.dns_servers\n      tags.%:                      \"6\" => \"14\"\n      tags.AppRole:                \"\" => \"CoreDNS\"\n      tags.Approval:               \"\" => \"Yes\"\n      tags.Channel:                \"\" => \"Cloud Services\"\n      tags.Compliance:             \"\" => \"NCDE\"\n      tags.CostCentre:             \"\" => \"C958958\"\n      tags.Environment:            \"\" => \"dev\"\n      tags.Escalation:             \"\" => \"Albie.VanDerMerwe@williamhill.com\"\n      tags.InstanceReplacement:    \"\" => \"true\"\n      tags.Owner:                  \"\" => \"Cloud Services\"\n      tags.Product:                \"\" => \"CoreDNS\"\n      tags.Tier:                   \"\" => \"Internal\"\n      tags.Version:                \"\" => \"1.28.0\"\n      tags.approle:                \"Core DNS\" => \"\"\n      tags.compliance:             \"NCDE\" => \"\"\n      tags.product:                \"dns\" => \"\"\n      tags.tier:                   \"internal\" => \"\"\n\n  ~ module.coredns.module.coredns-asg.aws_autoscaling_group.asg\n      launch_configuration:        \"coredns-asg20190117105931183000000001\" => \"${aws_launch_configuration.lc.name}\"\n      tags.#:                      \"23\" => \"19\"\n      tags.17.key:                 \"approle\" => \"envname\"\n      tags.17.value:               \"Core DNS\" => \"william-hill\"\n      tags.18.key:                 \"product\" => \"Service\"\n      tags.18.value:               \"dns\" => \"coredns\"\n      tags.19.%:                   \"3\" => \"0\"\n      tags.19.key:                 \"tier\" => \"\"\n      tags.19.propagate_at_launch: \"1\" => \"\"\n      tags.19.value:               \"Internal\" => \"\"\n      tags.20.%:                   \"3\" => \"0\"\n      tags.20.key:                 \"compliance\" => \"\"\n      tags.20.propagate_at_launch: \"1\" => \"\"\n      tags.20.value:               \"ncde\" => \"\"\n      tags.21.%:                   \"3\" => \"0\"\n      tags.21.key:                 \"envname\" => \"\"\n      tags.21.propagate_at_launch: \"1\" => \"\"\n      tags.21.value:               \"william-hill\" => \"\"\n      tags.22.%:                   \"3\" => \"0\"\n      tags.22.key:                 \"Service\" => \"\"\n      tags.22.propagate_at_launch: \"1\" => \"\"\n      tags.22.value:               \"coredns\" => \"\"\n\n-/+ module.coredns.module.coredns-asg.aws_launch_configuration.lc (new resource required)\n      id:                          \"coredns-asg20190117105931183000000001\" => <computed> (forces new resource)\n      associate_public_ip_address: \"false\" => \"false\"\n      ebs_block_device.#:          \"0\" => <computed>\n      ebs_optimized:               \"false\" => <computed>\n      enable_monitoring:           \"true\" => \"true\"\n      iam_instance_profile:        \"dev_coredns_iam_profile_default-profile\" => \"dev_coredns_iam_profile_default-profile\"\n      image_id:                    \"ami-05d09cf90b25d2bad\" => \"ami-048df0aaa28f1f084\" (forces new resource)\n      instance_type:               \"t2.medium\" => \"t2.medium\"\n      key_name:                    \"\" => <computed>\n      name:                        \"coredns-asg20190117105931183000000001\" => <computed>\n      name_prefix:                 \"coredns-asg\" => \"coredns-asg\"\n      root_block_device.#:         \"0\" => <computed>\n      security_groups.#:           \"2\" => \"2\"\n      security_groups.3527918019:  \"sg-002184a46723df56f\" => \"sg-002184a46723df56f\"\n      security_groups.3602543879:  \"sg-01b1d1aab55289227\" => \"sg-01b1d1aab55289227\"\n      user_data:                   \"9e4b9788584f65c0ff302a385a2c5b20dcbf8f8a\" => \"9e4b9788584f65c0ff302a385a2c5b20dcbf8f8a\"\n\n\nPlan: 1 to add, 5 to change, 1 to destroy.\n\n------------------------------------------------------------------------```",
      "state": "opened",
      "created_at": "2019-03-27T20:57:16.431Z",
      "updated_at": "2019-02-04T20:57:16.431Z",
      "target_branch": "develop",
      "source_branch": "feature/bump-tags",
      "upvotes": 0,
      "downvotes": 0,
      "author": {
        "name": "Magdalena Adamowicz",
        "username": "madamowicz",
        "id": 1454,
        "state": "active",
        "avatar_url": "https://secure.gravatar.com/avatar/4c9054ef12c56a546cbc8becbb214056?s=80&d=identicon",
        "web_url": "https://git.nonprod.williamhill.plc/madamowicz"
      },
      "assignee": null,
      "source_project_id": 9170,
      "target_project_id": 9170,
      "labels": [],
      "work_in_progress": false,
      "milestone": null,
      "merge_when_pipeline_succeeds": false,
      "merge_status": "can_be_merged",
      "sha": "3141592394a68d720a74ad38c8ff7f56d327894f",
      "merge_commit_sha": null,
      "user_notes_count": 0,
      "approvals_before_merge": null,
      "should_remove_source_branch": null,
      "force_remove_source_branch": false,
      "squash": false,
      "web_url": "https://git.nonprod.williamhill.plc/cloud-services/dns/merge_requests/4"
    },
    {
      "id": 99738,
      "iid": 3,
      "project_id": 9170,
      "title": "Standard tags",
      "description": "",
      "state": "merged",
      "created_at": "2019-03-26T20:57:16.431Z",
      "updated_at": "2019-01-15T11:45:47.755Z",
      "target_branch": "develop",
      "source_branch": "feature/StandardTags",
      "upvotes": 0,
      "downvotes": 0,
      "author": {
        "name": "Rob Lewis (Cloud Engineering and Operations)",
        "username": "rolewis",
        "id": 1415,
        "state": "active",
        "avatar_url": "https://git.nonprod.williamhill.plc/uploads/-/system/user/avatar/1415/avatar.png",
        "web_url": "https://git.nonprod.williamhill.plc/rolewis"
      },
      "assignee": null,
      "source_project_id": 9170,
      "target_project_id": 9170,
      "labels": [],
      "work_in_progress": false,
      "milestone": null,
      "merge_when_pipeline_succeeds": false,
      "merge_status": "can_be_merged",
      "sha": "aa8fd494f293b2688819eb839ba92baf43fb076a",
      "merge_commit_sha": "933c897dc7df4cc0491db22122881febc6102ccb",
      "user_notes_count": 0,
      "approvals_before_merge": null,
      "should_remove_source_branch": null,
      "force_remove_source_branch": false,
      "squash": false,
      "web_url": "https://git.nonprod.williamhill.plc/cloud-services/dns/merge_requests/3"
    },
    {
      "id": 96460,
      "iid": 2,
      "project_id": 9170,
      "title": "Update to encrypted AMI and tags",
      "description": "",
      "state": "merged",
      "created_at": "2019-03-25T20:57:16.431Z",
      "updated_at": "2018-12-13T13:33:35.795Z",
      "target_branch": "develop",
      "source_branch": "feature/encrypted_ami",
      "upvotes": 1,
      "downvotes": 0,
      "author": {
        "name": "Alastair Montgomery",
        "username": "amontgomery",
        "id": 40,
        "state": "active",
        "avatar_url": "https://git.nonprod.williamhill.plc/uploads/-/system/user/avatar/40/avatar.png",
        "web_url": "https://git.nonprod.williamhill.plc/amontgomery"
      },
      "assignee": null,
      "source_project_id": 9170,
      "target_project_id": 9170,
      "labels": [],
      "work_in_progress": false,
      "milestone": null,
      "merge_when_pipeline_succeeds": false,
      "merge_status": "can_be_merged",
      "sha": "08ccb08f07c3b898e7e7ccde622f3c204f303f2c",
      "merge_commit_sha": "040a714dd026d45c2918fcf459fa5bb7ca1e7656",
      "user_notes_count": 0,
      "approvals_before_merge": null,
      "should_remove_source_branch": null,
      "force_remove_source_branch": false,
      "squash": false,
      "web_url": "https://git.nonprod.williamhill.plc/cloud-services/dns/merge_requests/2"
    },
    {
      "id": 91213,
      "iid": 1,
      "project_id": 9170,
      "title": "Correct DNS now that account specific",
      "description": "",
      "state": "merged",
      "created_at": "2019-03-24T20:57:16.431Z",
      "updated_at": "2018-11-07T15:54:00.832Z",
      "target_branch": "develop",
      "source_branch": "feature/FixForCrossAcctDNS",
      "upvotes": 0,
      "downvotes": 0,
      "author": {
        "name": "Rob Lewis (Cloud Engineering and Operations)",
        "username": "rolewis",
        "id": 1415,
        "state": "active",
        "avatar_url": "https://git.nonprod.williamhill.plc/uploads/-/system/user/avatar/1415/avatar.png",
        "web_url": "https://git.nonprod.williamhill.plc/rolewis"
      },
      "assignee": null,
      "source_project_id": 9170,
      "target_project_id": 9170,
      "labels": [],
      "work_in_progress": false,
      "milestone": null,
      "merge_when_pipeline_succeeds": false,
      "merge_status": "can_be_merged",
      "sha": "c1aefe1b6089ffad43a37b04a65b22331c4a4d11",
      "merge_commit_sha": "42c8be23127339f7270addf9f1622ae450fddc80",
      "user_notes_count": 0,
      "approvals_before_merge": null,
      "should_remove_source_branch": null,
      "force_remove_source_branch": false,
      "squash": false,
      "web_url": "https://git.nonprod.williamhill.plc/cloud-services/dns/merge_requests/1"
    }
  ]

  module.exports = merge_requests