const projects = [
    {
        "id": 12015,
        "description": "For central products channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/centralproduct_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/centralproduct_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/centralproduct_aws",
        "name": "centralproduct_aws",
        "name_with_namespace": "infosec / centralproduct_aws",
        "path": "centralproduct_aws",
        "path_with_namespace": "infosec/centralproduct_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:04:12.002Z",
        "last_activity_at": "2019-03-15T12:04:12.002Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      },
      {
        "id": 12014,
        "description": "For core products channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/coreproduct_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/coreproduct_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/coreproduct_aws",
        "name": "coreproduct_aws",
        "name_with_namespace": "infosec / coreproduct_aws",
        "path": "coreproduct_aws",
        "path_with_namespace": "infosec/coreproduct_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:02:20.840Z",
        "last_activity_at": "2019-03-15T12:02:20.840Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      },
      {
        "id": 12013,
        "description": "For international channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/international_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/international_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/international_aws",
        "name": "international_aws",
        "name_with_namespace": "infosec / international_aws",
        "path": "international_aws",
        "path_with_namespace": "infosec/international_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:01:56.528Z",
        "last_activity_at": "2019-03-15T12:01:56.528Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      },
      {
        "id": 12012,
        "description": "For payments channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/payments_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/payments_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/payments_aws",
        "name": "payments_aws",
        "name_with_namespace": "infosec / payments_aws",
        "path": "payments_aws",
        "path_with_namespace": "infosec/payments_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:01:30.636Z",
        "last_activity_at": "2019-03-15T12:01:30.636Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      },
      {
        "id": 12011,
        "description": "For gaming channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/gaming_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/gaming_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/gaming_aws",
        "name": "gaming_aws",
        "name_with_namespace": "infosec / gaming_aws",
        "path": "gaming_aws",
        "path_with_namespace": "infosec/gaming_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:01:02.478Z",
        "last_activity_at": "2019-03-15T12:01:02.478Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      },
      {
        "id": 12010,
        "description": "For retail channel to deploy WHC firewall rules for AWS",
        "default_branch": "master",
        "tag_list": [],
        "public": true,
        "archived": false,
        "visibility_level": 20,
        "ssh_url_to_repo": "git@git.nonprod.williamhill.plc:infosec/retail_aws.git",
        "http_url_to_repo": "https://git.nonprod.williamhill.plc/infosec/retail_aws.git",
        "web_url": "https://git.nonprod.williamhill.plc/infosec/retail_aws",
        "name": "retail_aws",
        "name_with_namespace": "infosec / retail_aws",
        "path": "retail_aws",
        "path_with_namespace": "infosec/retail_aws",
        "container_registry_enabled": false,
        "issues_enabled": true,
        "merge_requests_enabled": true,
        "wiki_enabled": true,
        "builds_enabled": true,
        "snippets_enabled": true,
        "created_at": "2019-03-15T12:00:29.896Z",
        "last_activity_at": "2019-03-15T12:00:29.896Z",
        "shared_runners_enabled": true,
        "lfs_enabled": false,
        "creator_id": 510,
        "namespace": {
          "id": 13,
          "name": "infosec",
          "path": "infosec",
          "kind": "group",
          "full_path": "infosec",
          "parent_id": null,
          "members_count_with_descendants": 678,
          "shared_runners_minutes_limit": null,
          "plan": null
        },
        "avatar_url": null,
        "star_count": 0,
        "forks_count": 0,
        "open_issues_count": 0,
        "public_builds": true,
        "shared_with_groups": [],
        "only_allow_merge_if_build_succeeds": false,
        "repository_storage": "default",
        "request_access_enabled": false,
        "only_allow_merge_if_all_discussions_are_resolved": false,
        "approvals_before_merge": 0,
        "permissions": {
          "project_access": null,
          "group_access": {
            "access_level": 30,
            "notification_level": 3
          }
        }
      }
]

module.exports = projects